# -*- coding: utf-8 -*-
"""kadai_015

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MCfnSUAVzM9v2B496BkkO9KOEUuacpah
"""

class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def printinfo(self):
    print("名前：", self.name)
    print("年齢：", self.age)

# インスタンス化する
user = Human("侍太郎", 36)
# メソッドにアクセスして実行
user.printinfo()

