# -*- coding: utf-8 -*-
"""kadai_015

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MCfnSUAVzM9v2B496BkkO9KOEUuacpah
"""

class Human:
  # コンストラクタを定義する
  def __init__(self, name, age):
      self.name = name
      self.age = age

# インスタンス化する
user = Human("侍太郎", 36)

# printinfoを使用して出力する
def printinfo(neme, age):
    print("名前：", user.name)
    print("年齢：", user.age)
    return

#値を出力する
printinfo(user.name, user.age)