# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDlquenRARLs60NTne8uiZkPDA2lwc_h
"""

#上辺 = a / 下辺 = b / 高さ = c
a = 10
b = 20
c = 5

#公式：台形の面積 = (上辺＋下辺) × 高さ ÷ 2
menseki=(a + b) * c /2
print("台形の面積" +str(menseki) + "㎠")