# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xe0bo7y0XpGSGc0ZWg5ry0y2_MT2DJLd
"""

import random
var = random.randint(0, 100)
print(var)
#3と5の倍数
if var % 3 == 0 and var % 5 == 0:
    print("FizzBuzz")
#3の倍数
elif var % 3 == 0:
    print("Fizz")
#5の倍数
elif var % 5 == 0:
    print("Buzz")
#該当なし
else:
    print(var)