# -*- coding: utf-8 -*-
"""kadai_013

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bv7RX3nygwQalw6D7Meku7PiNepId-iS
"""

# 購入済みかどうかを判定する変数
purchased = True

# 戻り値を返す関数を定義する
def is_purchased():
    if (purchased):
        return True
    else:
        return False

# 戻り値を返す関数を条件式に使う（Trueであれば処理が実行される）
if (is_purchased()):
    def pay_total(price, tax):
      return price + (price * tax / 100)

total = pay_total(1000, 10)

print(f"{total}円")