# -*- coding: utf-8 -*-
"""kadai_013

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zoDsR09dWeWoK7PUAQpLTi7ybsyIJox
"""

# 商品を購入して、消費税を加えた計算結果を返す関数

# 購入済みかどうかを判定する変数
purchased = True

# 戻り値を返す関数を定義する
def is_purchased():
    if (purchased):
        return True
    else:
        return False

# 戻り値を返す関数を条件式に使う（Trueであれば処理が実行される）
if (is_purchased()):
    def calculate_total(price, tax):
      total = price + (price * tax / 100)
      print(f"{total}円")

calculate_total(1000,10)