# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zoDsR09dWeWoK7PUAQpLTi7ybsyIJox
"""

# 商品を購入して、消費税を加えた計算結果を返す関数
def calculate_total(price, TAX):
    total = price + (price * TAX / 100)
    print(f"{total}円")

calculate_total(1000,10)