# -*- coding: utf-8 -*-
"""kadai_014

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ahLMiw9p4HTi6S9VDfRrjJDI-pawXvxC
"""

price1 = 100
price2 = 200
tax = 1.1

def total():
    return price1 + price2

print(total() * tax)