# -*- coding: utf-8 -*-
"""kadai_017

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19D19JmZL0L9HsIXhuyQIWrBowJd_mS29
"""

# 名前(name)と年齢(age)の属性を持つHumanクラスを作成
class Human:
  def __init__(self, name, age):
    self.name = name
    self.age = age

# check_adult メソッドを作成
  def check_adult(self):
    # ageが20以上の場合に大人であること
    if self.age >= 20:
      print("{}は大人です。".format(self.name))
# そうでない場合に大人でないこと
    else:
      print("{}は大人ではありません。".format(self.name))

# Humanクラスのインスタンスを複数生成リスト
members = [
    Human("侍太郎", 36),
    Human("侍一郎", 20),
    Human("侍花子", 18)
]
# リストの要素数分だけcheck_adultメソッドにアクセスして実行
for member in members:
  member.check_adult()