# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-N6dKyD0wV5ZYN4qsfolcGJmWPi-8AAa
"""

#forを用いて繰り返し処理
list = ["水", "金", "地", "火", "木", "土", "天", "海", "冥"]
for value in list:
    print(value)

#whileを用いて繰り返し処理
len_list = len(list)

index = 0
while index < len_list:
  value = list[index]
  print(value)
  index = index + 1